"""empty message

Revision ID: 0e36c0ac63e6
Revises: b44a7620c64d
Create Date: 2020-01-18 16:20:54.621575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e36c0ac63e6'
down_revision = 'b44a7620c64d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('matricule_sup', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'matricule_sup')
    # ### end Alembic commands ###
