"""empty message

Revision ID: 1a112338eb57
Revises: e99f6b730954
Create Date: 2020-02-03 16:58:06.851793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a112338eb57'
down_revision = 'e99f6b730954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demande_mobile_temp', sa.Column('complement_demande', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demande_mobile_temp', 'complement_demande')
    # ### end Alembic commands ###
