"""empty message

Revision ID: 1d0497ddf138
Revises: 5a849b6431a4
Create Date: 2020-01-21 09:51:03.610700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d0497ddf138'
down_revision = '5a849b6431a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demande', 'etat_demande')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demande', sa.Column('etat_demande', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
