"""empty message

Revision ID: 2063aa7d0b0a
Revises: 402c2e0d093e
Create Date: 2020-01-22 13:27:23.279622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2063aa7d0b0a'
down_revision = '402c2e0d093e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demande_mobile_perm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motif', sa.Text(), nullable=False),
    sa.Column('nom_projet', sa.String(length=120), nullable=False),
    sa.Column('puces', sa.Integer(), nullable=False),
    sa.Column('pilote', sa.String(length=120), nullable=False),
    sa.Column('caracteristiques', sa.Text(), nullable=False),
    sa.Column('etat_demande', sa.String(length=30), nullable=True),
    sa.Column('date_demande', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parc_id', sa.Integer(), nullable=False),
    sa.Column('offre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offre_id'], ['offre.id'], ),
    sa.ForeignKeyConstraint(['parc_id'], ['parc.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('demande_mobile_temp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motif', sa.Text(), nullable=False),
    sa.Column('nom_projet', sa.String(length=120), nullable=False),
    sa.Column('puces', sa.Integer(), nullable=False),
    sa.Column('pilote', sa.String(length=120), nullable=False),
    sa.Column('caracteristiques', sa.Text(), nullable=False),
    sa.Column('etat_demande', sa.String(length=30), nullable=True),
    sa.Column('date_demande', sa.DateTime(), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_fin', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parc_id', sa.Integer(), nullable=False),
    sa.Column('offre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offre_id'], ['offre.id'], ),
    sa.ForeignKeyConstraint(['parc_id'], ['parc.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_index('id', table_name='demande')
    op.drop_table('demande')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demande',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('motif', mysql.TEXT(), nullable=False),
    sa.Column('nom_projet', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('puces', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('pilote', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('caracteristiques', mysql.TEXT(), nullable=False),
    sa.Column('date_demande', mysql.DATETIME(), nullable=False),
    sa.Column('date_debut', mysql.DATETIME(), nullable=True),
    sa.Column('date_fin', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('parc_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('offre_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('etat_demande', mysql.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['offre_id'], ['offre.id'], name='demande_ibfk_1'),
    sa.ForeignKeyConstraint(['parc_id'], ['parc.id'], name='demande_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='demande_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'demande', ['id'], unique=True)
    op.drop_table('demande_mobile_temp')
    op.drop_table('demande_mobile_perm')
    # ### end Alembic commands ###
