"""empty message

Revision ID: 402c2e0d093e
Revises: 1d0497ddf138
Create Date: 2020-01-21 09:51:35.674581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402c2e0d093e'
down_revision = '1d0497ddf138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demande', sa.Column('etat_demande', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demande', 'etat_demande')
    # ### end Alembic commands ###
