"""empty message

Revision ID: 6d09543fc52d
Revises: e440860a4151
Create Date: 2020-02-06 14:18:08.994517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d09543fc52d'
down_revision = 'e440860a4151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('demande_mobile_perm', 'complement_demande',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('demande_mobile_temp', 'complement_demande',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('demande_mobile_temp', 'complement_demande',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('demande_mobile_perm', 'complement_demande',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
