"""empty message

Revision ID: d41506006835
Revises: 3aee5ce64f75
Create Date: 2020-02-22 14:44:22.976986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41506006835'
down_revision = '3aee5ce64f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facturation_mobile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mois', sa.String(length=20), nullable=False),
    sa.Column('total', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facturation_mobile')
    # ### end Alembic commands ###
