"""empty message

Revision ID: dc037325373c
Revises: 2063aa7d0b0a
Create Date: 2020-01-22 15:53:19.804296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc037325373c'
down_revision = '2063aa7d0b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parc', sa.Column('detail_parc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parc', 'detail_parc')
    # ### end Alembic commands ###
