"""empty message

Revision ID: e440860a4151
Revises: 1a112338eb57
Create Date: 2020-02-05 09:29:10.380238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e440860a4151'
down_revision = '1a112338eb57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demande_mobile_perm', sa.Column('complement_demande', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demande_mobile_perm', 'complement_demande')
    # ### end Alembic commands ###
