"""empty message

Revision ID: e99f6b730954
Revises: dffd124ae568
Create Date: 2020-01-31 11:16:25.548398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99f6b730954'
down_revision = 'dffd124ae568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demande_mobile_perm', sa.Column('date_debut', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demande_mobile_perm', 'date_debut')
    # ### end Alembic commands ###
